### ISSUE TITLE
chatgpt & pytorch

### ISSUE THREAD

**Issue by Bailey-24** [ohnghb99/tabletop-SayCan#1]
Hi,
  the origin saycan use gpt3, but I only got the gpt3.5 API key, can it run?

the origin saycan use tensorflow, but I'm familiar with PyTorch, will you change the code to pytorch?

Thanks.

**Comment by ohnghb99** [comment]
Hi, I see now.

1. As far as I know, you can use both GPT-3 and GPT-3.5 if you get an API key. Anyway, when I tested text-ada-001 for gpt-3 model and text-davinci-002 for gpt3.5 model using one API key, it ran successfully.

3. sorry, I don't think I'll change it since I'm only testing in my co-lab.

thanks for watch my code. 👍🏻
